services:
  # Banco de Dados
  postgres:
    image: postgres:15-alpine
    container_name: pc_database
    environment:
      POSTGRES_DB: primeiracasa
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # API Spring Boot
  api:
    build: .
    container_name: pc_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/primeiracasa
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - DDL_AUTO=update

volumes:
  postgres_data: