spring.application.name=primeira-casa-backend

# Database Configuration - Supabase PostgreSQL
# src/main/resources/application.properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=10MB

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT key
api.security.token.secret=${JWT_SECRET}
api.security.token.expiration=3600000

# url permitidas(render, local web, local testes, local android, local ios
app.cors.allowed-origins=https://primeiracasa-frontend.vercel.app,http://localhost:5173,http://localhost:8080,http://10.0.2.2:8080,http://192.168.1.5:8080,http://localhost:8081,http://localhost:19006